version: "3"

x-container-common: &container-common
  restart: ${CONTAINER_RESTART:-on-failure}
  networks:
    - deps-kafka

services:
  zookeeper:
    <<: *container-common
    image: confluentinc/cp-zookeeper:${ZOOKEEPER_IMAGE_VERSION:-latest}
    container_name: zookeeper
    ports:
      - ${ZOOKEEPER_EXTERNAL_PORT:-2181}:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT:-32181}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME:-2000}

  kafka:
    <<: *container-common
    image: confluentinc/cp-kafka:${KAFKA_IMAGE_VERSION:-latest}
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_EXTERNAL_PORT:-32181}
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://${KAFKA_EXTERNAL_HOSTNAME:-localhost}:${KAFKA_EXTERNAL_PORT:-9092}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "kafka:9092"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s

  kafka-ui:
    <<: *container-common
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: remote-local-machine
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:${ZOOKEEPER_EXTERNAL_PORT:-2181}

networks:
  deps-kafka:
    name: deps-kafka-dev
    driver: bridge